export const allBooks = [
  {
    id: 0,
    status: 'Available',
    title: 'The Effective Engineer',
    authors: ['Edmond Lau'],
    year: '2009',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 1,
    status: 'Borrowed Out',
    title: 'Built To Last',
    authors: ['Jim Collins', 'Jerry I. Porras'],
    year: '2001',
    genre: ['Business', 'Entrepreneurship'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 2,
    status: 'Available',
    title: 'The Lean Startup',
    authors: ['Eric Reiss'],
    year: '2005',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 3,
    status: 'Available',
    title: 'Effective Python',
    authors: ['Diomidis Spinellis'],
    year: null,
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 4,
    status: 'Available',
    title: 'Big Magic',
    authors: ['Elizabeth Gilbert'],
    year: '2014',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 5,
    status: 'Available',
    title: 'Effective Python',
    authors: ['Diomidis Spinellis'],
    year: null,
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 6,
    status: 'Available',
    title: 'The Effective Engineer',
    authors: ['Edmond Lau'],
    year: '2009',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 0,
    status: 'Borrowed Out',
    title: 'Built To Last',
    authors: ['Jim Collins', 'Jerry I. Porras'],
    year: '2001',
    genre: ['Business', 'Entrepreneurship'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 7,
    status: 'Available',
    title: 'The Lean Startup',
    authors: ['Eric Reiss'],
    year: '2005',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 8,
    status: 'Available',
    title: 'Effective Python',
    authors: ['Diomidis Spinellis'],
    year: null,
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 9,
    status: 'Available',
    title: 'Big Magic',
    authors: ['Elizabeth Gilbert'],
    year: '2014',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 10,
    status: 'Available',
    title: 'The Effective Engineer',
    authors: ['Edmond Lau'],
    year: '2009',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 11,
    status: 'Available',
    title: 'The Lean Startup',
    authors: ['Eric Reiss'],
    year: '2005',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
];

export const recentlyAddedBooks = [
  {
    id: 0,
    status: 'Available',
    title: 'The Effective Engineer',
    authors: ['Edmond Lau'],
    year: '2009',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 2,
    status: 'Borrowed Out',
    title: 'Built To Last',
    authors: ['Jim Collins', 'Jerry I. Porras'],
    year: '2001',
    genre: ['Business', 'Entrepreneurship'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 3,
    status: 'Available',
    title: 'The Lean Startup',
    authors: ['Eric Reiss'],
    year: '2005',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 4,
    status: 'Available',
    title: 'Effective Python',
    authors: ['Diomidis Spinellis'],
    year: null,
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 5,
    status: 'Available',
    title: 'Big Magic',
    authors: ['Elizabeth Gilbert'],
    year: '2014',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
];

export const featuredBooks = [
  {
    id: 0,
    status: 'Available',
    title: 'Big Magic',
    authors: ['Elizabeth Gilbert'],
    year: '2014',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 1,
    status: 'Available',
    title: 'Effective Python',
    authors: ['Diomidis Spinellis'],
    year: null,
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 2,
    status: 'Borrowed Out',
    title: 'Built To Last',
    authors: ['Jim Collins', 'Jerry I. Porras'],
    year: '2001',
    genre: ['Business', 'Entrepreneurship'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 3,
    status: 'Available',
    title: 'The Lean Startup',
    authors: ['Eric Reiss'],
    year: '2005',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 4,
    status: 'Available',
    title: 'The Effective Engineer',
    authors: ['Edmond Lau'],
    year: '2009',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 5,
    status: 'Available',
    title: 'Big Magic',
    authors: ['Elizabeth Gilbert'],
    year: '2014',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 6,
    status: 'Available',
    title: 'Effective Python',
    authors: ['Diomidis Spinellis'],
    year: null,
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 7,
    status: 'Borrowed Out',
    title: 'Built To Last',
    authors: ['Jim Collins', 'Jerry I. Porras'],
    year: '2001',
    genre: ['Business', 'Entrepreneurship'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 8,
    status: 'Available',
    title: 'The Lean Startup',
    authors: ['Eric Reiss'],
    year: '2005',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
  {
    id: 9,
    status: 'Available',
    title: 'The Effective Engineer',
    authors: ['Edmond Lau'],
    year: '2009',
    genre: ['Motivational'],
    labels: ['Creative', 'Self-help'],
    stats: {
      ratings: 4.0,
      readers: 31,
      likes: 29,
    },
  },
];
